apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-cert-manager-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-cert-manager-operator
  template:
    metadata:
      labels:
        name: ibm-cert-manager-operator
    spec:
      imagePullSecrets:
      - name: pull-secret-1
      serviceAccountName: ibm-cert-manager-operator
      containers:
        - name: ibm-cert-manager-operator
          # Replace this with the built image name
          image: IMAGE_NAME
          command:
          - ibm-cert-manager-operator
          args:
          - --zap-level=1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-cert-manager-operator"
